return {
  indentLine_enabled = 1,
  char = "▏",
  -- char = "│",
  -- context_char = "│",
  -- context_char = "▏",
  filetype_exclude = {
    "",
    "NvimTree",
    "TelescopePrompt",
    "TelescopeResults",
    "Trouble",
    "aerial",
    "alpha",
    "dashboard",
    "help",
    "lazy",
    "lazyterm",
    "lspinfo",
    "mason",
    "neo-tree",
    "neogitstatus",
    "notify",
    "nvcheatsheet",
    "nvdash",
    "startify",
    "terminal",
    "toggleterm",
  },
  context_patterns = {
    "class",
    "return",
    "function",
    "method",
    "^if",
    "^while",
    "jsx_element",
    "^for",
    "^object",
    "^table",
    "block",
    "arguments",
    "if_statement",
    "else_clause",
    "jsx_element",
    "jsx_self_closing_element",
    "try_statement",
    "catch_clause",
    "import_statement",
    "operation_type",
  },
  buftype_exclude                = { "nofile", "terminal" },
  show_trailing_blankline_indent = false,
  show_first_indent_level        = false,
  -- NOTE: xx treesittere does too much highlighting I think; xx switch these
  -- NOTE: to true if you end up enabling treesitter...
  show_current_context           = false,
  show_current_context_start     = false,
  use_treesitter                 = false,
}
