local map = vim.keymap.set

return function()
  map("v", "<leader>at",  ":Tabularize /&<CR>", { desc = "" })
  map("n", "<leader>at",  ":Tabularize /&<CR>", { desc = "" })

  map("v", "<leader>a#",  ":Tabularize /#/l1r1<CR>", { desc = "" })
  map("v", "<leader>a%",  ":Tabularize /%/l1r1<CR>", { desc = "" })
  map("v", "<leader>a&",  ":Tabularize /&/l1r1<CR>", { desc = "" })
  map("v", "<leader>a*",  ":Tabularize /*/l1r1<CR>", { desc = "" })
  map("v", "<leader>a=",  ":Tabularize /=/l1r1<CR>", { desc = "" })
  map("v", "<leader>a-",  ":Tabularize /-/l1r1<CR>", { desc = "" })
  map("v", "<leader>a,",  ":Tabularize /,/l1r1<CR>", { desc = "" })
  map("v", '<leader>a"',  ':Tabularize /"/l1r1<CR>', { desc = "" })
  map("v", "<leader>a:",  ":Tabularize /:/l1r1<CR>", { desc = "" })
  map("v", "<leader>a;",  ":Tabularize /;/l1r1<CR>", { desc = "" })
  map("v", "<leader>a$",  ":Tabularize /$/l1r1<CR>", { desc = "" })
  map("v", "<leader>a/",  ":Tabularize /\\/\\/\\+/l1r1<CR>",   { desc = "" })
  map("v", "<leader>a\\", ":Tabularize /\\\\\\\\\\+/l1r1<CR>", { desc = "" })

  map("n", "<leader>a#",  "mm:Tabularize /#/l1r1<CR>`m", { desc = "" })
  map("n", "<leader>a%",  "mm:Tabularize /%/l1r1<CR>`m", { desc = "" })
  map("n", "<leader>a&",  "mm:Tabularize /&/l1r1<CR>`m", { desc = "" })
  map("n", "<leader>a*",  "mm:Tabularize /*/l1r1<CR>`m", { desc = "" })
  map("n", "<leader>a=",  "mm:Tabularize /=/l1r1<CR>`m", { desc = "" })
  map("n", "<leader>a-",  "mm:Tabularize /-/l1r1<CR>`m", { desc = "" })
  map("n", "<leader>a,",  "mm:Tabularize /,/l1r1<CR>`m", { desc = "" })
  map("n", '<leader>a"',  'mm:Tabularize /"/l1r1<CR>`m', { desc = "" })
  map("n", "<leader>a:",  "mm:Tabularize /:/l1r1<CR>`m", { desc = "" })
  map("n", "<leader>a;",  "mm:Tabularize /;/l1r1<CR>`m", { desc = "" })
  map("n", "<leader>a$",  "mm:Tabularize /$/l1r1<CR>`m", { desc = "" })
  map("n", "<leader>a/",  "mm:Tabularize /\\/\\/\\+/l1r1<CR>`m",   { desc = "" })
  map("n", "<leader>a\\", "mm:Tabularize /\\\\\\\\\\+/l1r1<CR>`m", { desc = "" })

  map("v", "<leader>z#",  ":Tabularize /#\\zs/l0r1<CR>", { desc = "" })
  map("v", "<leader>z%",  ":Tabularize /%\\zs/l0r1<CR>", { desc = "" })
  map("v", "<leader>z&",  ":Tabularize /&\\zs/l0r1<CR>", { desc = "" })
  map("v", "<leader>z*",  ":Tabularize /*\\zs/l0r1<CR>", { desc = "" })
  map("v", "<leader>z=",  ":Tabularize /=\\zs/l0r1<CR>", { desc = "" })
  map("v", '<leader>z"',  ':Tabularize /"\\zs/l0r1<CR>', { desc = "" })
  map("v", "<leader>z:",  ":Tabularize /:\\zs/l0r1<CR>", { desc = "" })
  map("v", "<leader>z;",  ":Tabularize /;\\zs/l0r1<CR>", { desc = "" })
  map("v", "<leader>z$",  ":Tabularize /$\\zs/l0r1<CR>", { desc = "" })
  map("v", "<leader>z/",  ":Tabularize /\\/\\/\\+\\zs/l0r1<CR>",   { desc = "" })
  map("v", "<leader>z/",  ":Tabularize /\\\\\\\\\\+\\zs/l0r1<CR>", { desc = "" })

  map("n", "<leader>z#",  "mm:Tabularize /#\\zs/l0r1<CR>`m", { desc = "" })
  map("n", "<leader>z%",  "mm:Tabularize /%\\zs/l0r1<CR>`m", { desc = "" })
  map("n", "<leader>z&",  "mm:Tabularize /&\\zs/l0r1<CR>`m", { desc = "" })
  map("n", "<leader>z*",  "mm:Tabularize /*\\zs/l0r1<CR>`m", { desc = "" })
  map("n", "<leader>z=",  "mm:Tabularize /=\\zs/l0r1<CR>`m", { desc = "" })
  map("n", "<leader>z-",  "mm:Tabularize /-\\zs/l0r1<CR>`m", { desc = "" })
  map("n", "<leader>z,",  "mm:Tabularize /,\\zs/l0r1<CR>`m", { desc = "" })
  map("n", '<leader>z"',  'mm:Tabularize /"\\zs/l0r1<CR>`m', { desc = "" })
  map("n", "<leader>z:",  "mm:Tabularize /:\\zs/l0r1<CR>`m", { desc = "" })
  map("n", "<leader>z;",  "mm:Tabularize /;\\zs/l0r1<CR>`m", { desc = "" })
  map("n", "<leader>z$",  "mm:Tabularize /$\\zs/l0r1<CR>`m", { desc = "" })
  map("n", "<leader>z/",  "mm:Tabularize /\\/\\/\\+\\zs/l0r1<CR>`m",   { desc = "" })
  map("n", "<leader>z\\", "mm:Tabularize /\\\\\\\\\\+\\zs/l0r1<CR>`m", { desc = "" })
end
